baseurl: ""
permalink: none
markdown: redcarpet
redcarpet:
    extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
highlighter: pygments
safe: true
rouge: true
excerpt_separator: "\n\n\n"
paginate: 5
sitemapurl: "http://vaqeteart.github.io"
