baseurl: ""
permalink: none
markdown: rdiscount
redcarpet:
    extensions: [tables]
highlighter: pygments
safe: true
rouge: true
excerpt_separator: "\n\n\n"
paginate: 5
sitemapurl: "http://vaqeteart.github.io"
