baseurl: ""
permalink: none
markdown: kramdown
kramdown:
  input:  GFM
    use_coderay: true
highlighter: pygments
safe: true
rouge: true
excerpt_separator: "\n\n\n"
paginate: 5
sitemapurl: "http://vaqeteart.github.io"
